# Travis configuration for etl-worker.
#
# etl-worker is a Go project supporting release automation to mlab-sandbox
# for a single branch in the m-lab/etl repository. The steps it takes are:
#
#  * decrypt service account credentials
#  * install the Google Cloud SDK command line tools (gcloud)
#  * cache the gcloud installation and setup
#  * test and build the go code
#  * on success, deploy the result when the origin branch matches a supported
#    deployment target.

dist: bionic
language: go
go:
 - "1.13.8"

env:
- PATH=$PATH:$HOME/gopath/bin

before_install:

# Coverage tools
- go get github.com/mattn/goveralls

- echo Branch is ${TRAVIS_BRANCH} and Tag is $TRAVIS_TAG

# Install gcloud, for integration tests.
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- source "${HOME}/google-cloud-sdk/path.bash.inc"

# These directories will be cached on successful "script" builds, and restored,
# if available, to save time on future builds.
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
  # Install kexpand templating tool. Only works from HEAD.
- go get github.com/kopeio/kexpand
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl

# Get dependencies
- cd $TRAVIS_BUILD_DIR
- go get -v -t ./... || go get -v -t ./...

# List submodule versions
- git submodule

script:
- go get -v ./...
- go test -v -coverprofile=profile.cov ./...
- EC=$[ $EC || $? ] ;
# Go back to the root build dir
- cd $TRAVIS_BUILD_DIR
- echo "summary status $EC" ;
- if [[ $EC != 0 ]]; then false; fi ;

# Coveralls
# Run "unit tests" with coverage.

# Coveralls
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci || true

deploy:
######################################################################
#  Sandbox deployment
######################################################################

## Service: queue-pusher -- AppEngine Standard Environment.
## Removed for issue https://github.com/m-lab/etl/issues/751
- provider: script
  script:
    GOPATH=$HOME/go111 $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-sandbox
       SERVICE_ACCOUNT_mlab_sandbox $TRAVIS_BUILD_DIR/
  skip_cleanup: true
  on:
    repo: m-lab/etl-queue-pusher
    all_branches: true
    condition: $TRAVIS_BRANCH == qp-sandbox-*

######################################################################
#  Staging deployment
######################################################################
- provider: script
  script:
    $TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_staging
    && GOPATH=$HOME/go111 $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging
       SERVICE_ACCOUNT_mlab_staging $TRAVIS_BUILD_DIR/
  skip_cleanup: true
  on:
    repo: m-lab/etl-queue-pusher
    branch: master

######################################################################
#  Production deployment
######################################################################
- provider: script
  script:
    $TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_oti
    && GOPATH=$HOME/go111 $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-oti
       SERVICE_ACCOUNT_mlab_oti $TRAVIS_BUILD_DIR/appengine/queue_pusher
  skip_cleanup: true
  on:
    repo: m-lab/etl-queue-pusher
    all_branches: true
    condition: $TRAVIS_TAG == small-prod-* || $TRAVIS_TAG == prod-*
